apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mikie\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: redis-cluster-init
  name: redis-cluster-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-cluster-init
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mikie\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: redis-cluster-init
    spec:
      containers:
        - command:
            - bash
            - -c
            - ' sleep 10; echo yes | redis-cli --user openvsx --cluster create  redis-node-1:7000 redis-node-2:7000 redis-node-3:7000  redis-node-4:7000 redis-node-5:7000 redis-node-6:7000  --cluster-replicas 1'
          env:
            - name: REDISCLI_AUTH
              value: openvsx
          image: redis:7.2
          name: redis-cluster-init
      restartPolicy: Always
