apiVersion: v1
data:
  redis.conf: |-
    # Configuration for Redis nodes in docker-compose.yml
    port 7000
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    user default off
    user openvsx on >openvsx ~* +@all
    masteruser openvsx
    masterauth openvsx
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: redis-node-6
  name: redis-node-6-cm0
